### ISSUE TITLE
V8 and blink use different protocol.json files

### ISSUE THREAD

**Issue by nojvek** [RemoteDebug/remotedebug-compatibility-tables#3]
Latest ones are here: https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/platform/v8_inspector/js_protocol.json

https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/inspector/browser_protocol.json

**Comment by kdzwinel** [comment]
Note that these protocol files do not overlap - e.g. there is no Runtime section in the browser_protocol even though Chrome supports it. In other words:

Chrome = js_protocol.json + browser_protocol.json
V8 = js_protocol.json

**Comment by auchenberg** [comment]
Fixed in https://github.com/RemoteDebug/remotedebug-compatibility-tables/commit/97d178cfeef02edcf8ee7697f666a69099c478ca
